language: python
python:
 - "3.5"
cache: pip
services:
  - postgresql
install:
 - pip install -r requirements.txt
 - pip install coveralls
before_script:

   - export SECRET_KEY='thisisasecretkey'
   - export DB_NAME="test_db"
   - psql -c 'create database test_db;' -U postgres
script:
 - pytest app/test/
after_success:
 - coveralls
  